export const BALANCE_REQUEST = "BALANCE_REQUEST";
export const BALANCE_SUCCESS = "BALANCE_SUCCESS";
export const BALANCE_FAILURE = "BALANCE_FAILURE";

export const CHECK_SUB_REQUEST = "CHECK_SUB_REQUEST";
export const CHECK_SUB_SUCCESS = "CHECK_SUB_SUCCESS";
export const CHECK_SUB_FAILURE = "CHECK_SUB_FAILURE";

export const CHECK_PR_PAY_REQUEST = "CHECK_PR_PAY_REQUEST";
export const CHECK_PR_PAY_SUCCESS = "CHECK_PR_PAY_SUCCESS";
export const CHECK_PR_PAY_FAILURE = "CHECK_PR_PAY_FAILURE";
