export const CHECK_EMAIL_REQUEST = "CHECK_TRADE_ACCT_REQUEST";
export const CHECK_EMAIL_SUCCESS = "CHECK_TRADE_ACCT_SUCCESS";
export const CHECK_EMAIL_FAILURE = "CHECK_TRADE_ACCT_FAILURE";

export const ENABLE_EMAIL_REQUEST = "ENABLE_TRADE_ACCT_REQUEST";
export const ENABLE_EMAIL_SUCCESS = "ENABLE_TRADE_ACCT_SUCCESS";
export const ENABLE_EMAIL_FAILURE = "ENABLE_TRADE_ACCT_FAILURE";

export const DISABLE_EMAIL_REQUEST = "DISABLE_TRADE_ACCT_REQUEST";
export const DISABLE_EMAIL_SUCCESS = "DISABLE_TRADE_ACCT_SUCCESS";
export const DISABLE_EMAIL_FAILURE = "DISABLE_TRADE_ACCT_FAILURE";
