export const GET_INVOICE_LIST_REQUEST = "GET_INVOICE_LIST_REQUEST";
export const GET_INVOICE_LIST_SUCCESS = "GET_INVOICE_LIST_SUCCESS";
export const GET_INVOICE_LIST_FAILURE = "GET_INVOICE_LIST_FAILURE";

export const GET_SINGLE_INVOICE_REQUEST = "GET_SINGLE_INVOICE_REQUEST";
export const GET_SINGLE_INVOICE_SUCCESS = "GET_SINGLE_INVOICE_SUCCESS";
export const GET_SINGLE_INVOICE_FAILURE = "GET_SINGLE_INVOICE_FAILURE";

export const MAKE_PAYMENT_REQUEST = "MAKE_PAYMENT_REQUEST";
export const MAKE_PAYMENT_SUCCESS = "MAKE_PAYMENT_SUCCESS";
export const MAKE_PAYMENT_FAILURE = "MAKE_PAYMENT_FAILURE";

export const COUPON_REQUEST = "COUPON_REQUEST";
export const COUPON_SUCCESS = "COUPON_SUCCESS";
export const COUPON_FAILURE = "COUPON_FAILURE";
