export const REFERRAL_REQUEST = "REFERRAL_REQUEST";
export const REFERRAL_SUCCESS = "REFERRAL_SUCCESS";
export const REFERRAL_FAILURE = "REFERRAL_FAILURE";

export const REFERRAL_STATS_REQUEST = "REFERRAL_STATS_REQUEST";
export const REFERRAL_STATS_SUCCESS = "REFERRAL_STATS_SUCCESS";
export const REFERRAL_STATS_FAILURE = "REFERRAL_STATS_FAILURE";

export const WITHDRAW_REQUEST = "WITHDRAW_REQUEST";
export const WITHDRAW_SUCCESS = "WITHDRAW_SUCCESS";
export const WITHDRAW_FAILURE = "WITHDRAW_FAILURE";
