export const CHECK_TRADE_ACCT_REQUEST = "CHECK_TRADE_ACCT_REQUEST";
export const CHECK_TRADE_ACCT_SUCCESS = "CHECK_TRADE_ACCT_SUCCESS";
export const CHECK_TRADE_ACCT_FAILURE = "CHECK_TRADE_ACCT_FAILURE";

export const ADD_TRADE_ACCT_REQUEST = "ADD_TRADE_ACCT_REQUEST";
export const ADD_TRADE_ACCT_SUCCESS = "ADD_TRADE_ACCT_SUCCESS";
export const ADD_TRADE_ACCT_FAILURE = "ADD_TRADE_ACCT_FAILURE";

export const ENABLE_TRADE_ACCT_REQUEST = "ENABLE_TRADE_ACCT_REQUEST";
export const ENABLE_TRADE_ACCT_SUCCESS = "ENABLE_TRADE_ACCT_SUCCESS";
export const ENABLE_TRADE_ACCT_FAILURE = "ENABLE_TRADE_ACCT_FAILURE";

export const DISABLE_TRADE_ACCT_REQUEST = "DISABLE_TRADE_ACCT_REQUEST";
export const DISABLE_TRADE_ACCT_SUCCESS = "DISABLE_TRADE_ACCT_SUCCESS";
export const DISABLE_TRADE_ACCT_FAILURE = "DISABLE_TRADE_ACCT_FAILURE";

export const DELETE_TRADE_ACCT_REQUEST = "DELETE_TRADE_ACCT_REQUEST";
export const DELETE_TRADE_ACCT_SUCCESS = "DELETE_TRADE_ACCT_SUCCESS";
export const DELETE_TRADE_ACCT_FAILURE = "DELETE_TRADE_ACCT_FAILURE";
