export const UPDATE_PROFILE_REQUEST = "UPDATE_PROFILE_REQUEST";
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_FAILURE = "UPDATE_PROFILE_FAILURE";

export const UPDATE_PASSWORD_REQUEST = "UPDATE_PASSWORD_REQUEST";
export const UPDATE_PASSWORD_SUCCESS = "UPDATE_PASSWORD_SUCCESS";
export const UPDATE_PASSWORD_FAILURE = "UPDATE_PASSWORD_FAILURE";

export const GENERATE_OTP_REQUEST = "GENERATE_OTP_REQUEST";
export const GENERATE_OTP_SUCCESS = "GENERATE_OTP_SUCCESS";
export const GENERATE_OTP_FAILURE = "GENERATE_OTP_FAILURE";

export const UPDATE_WITHDRAWALADDRESS_REQUEST =
  "UPDATE_WITHDRAWALADDRESS_REQUEST";
export const UPDATE_WITHDRAWALADDRESS_SUCCESS =
  "UPDATE_WITHDRAWALADDRESS_SUCCESS";
export const UPDATE_WITHDRAWALADDRESS_FAILURE =
  "UPDATE_WITHDRAWALADDRESS_FAILURE";
